import log from "../../lib/logger"
import {
  CommandInteraction,
  PermissionFlagsBits,
  SlashCommandBuilder,
} from "discord.js"

export const insult = {
  command: new SlashCommandBuilder()
    .setName("insult")
    .setDescription("Insults a user.")
    .addUserOption((option) =>
      option.setName("user").setDescription("The user to insult")
    )
    .setDefaultMemberPermissions(PermissionFlagsBits.SendMessages),
  async execute(interaction: CommandInteraction) {
    // @ts-ignore
    const user = interaction.options.getUser("user")
    // Get random Insult:
    const randomInsult = Insults[Math.floor(Math.random() * Insults.length)]
    await interaction.reply(`${user} ${randomInsult}.`)
    log(`${user?.username} has been insulted.`)
  },
}

// The preceeding text was originally published by Prawn Song Records at www.primussucks.com
let Insults = [
  `You are swine you vulgar little maggot. Don't you know that you are pathetic? You worthless bag of filth. As we say in California, I'll bet you couldn't pour piss out of a boot with instructions on the heel. You are a canker. A sore that won't go away. A zit on the butt of society. I would rather kiss a lawyer than be seen with you.`,
  `You are a fiend and a coward, and you have bad breath. You are degenerate, noxious and depraved. I feel debased just for knowing you exist. I despise everything about you. You are a bloody nardless newbie twit protohominid chromosomally aberrant caricature of a coprophagic cloacal parasitic pond scum and I wish you would go away.`,
  `You're a putrescence mass, a walking vomit. You are a spineless little worm deserving nothing but the profoundest contempt. You are a jerk, a cad, a weasel. Your life is a monument to stupidity. You are a stench, a revulsion, a big suck on a sour lemon.`,
  `You are a bleating fool, a curdled staggering mutant dwarf smeared richly with the effluvia and offal accompanying your alleged birth into this world. An insensate, blinking calf, meaningful to nobody, abandoned by the puke-drooling, giggling beasts who sired you and then killed themselves in recognition of what they had done.`,
  `I will never get over the embarrassment of belonging to the same species as you. You are a monster, an ogre, a malformity. I barf at the very thought of you. You have all the appeal of a paper cut. Lepers avoid you. Because off your face the rabbit population actually decreased. You are vile, worthless, less than nothing. You are a weed, a fungus, the dregs of this earth. And did I mention you smell?`,
  `If you aren't an idiot, you made a world-class effort at simulating one.`,
  `You snail-skulled little rabbit. Would that a hawk pick you up, drive its beak into your brain, and upon finding it rancid set you loose to fly briefly before spattering the ocean rocks with the frothy pink shame of your ignoble blood. May you choke on the queasy, convulsing nausea of your own trite, foolish beliefs.`,
  `You are weary, stale, flat and unprofitable. You are grimy, squalid, nasty and profane. You are foul and disgusting. You're a fool, an ignoramus. Monkeys look down on you. Even sheep won't have sex with you. You are unreservedly pathetic, starved for attention, and lost in a land that reality forgot.`,
  `You are a waste of flesh. You have no rhythm. You are ridiculous and obnoxious. You are the moral equivalent of a leech. You are a living emptiness, a meaningless void. You are sour and senile. You are a disease, you puerile one-handed slack-jawed drooling meatslapper.`,
  `On a good day you're a half-wit. You remind me of drool. You are deficient in all that lends character. You have the personality of wallpaper. You are dank and filthy. You are asinine and benighted. You are the source of all unpleasantness. You spread misery and sorrow wherever you go.`,
  `I cannot believe how incredibly stupid you are. I mean rock-hard stupid. Dehydrated-rock-hard stupid. Stupid so stupid that it goes way beyond the stupid we know into a whole different dimension of stupid. You are trans-stupid stupid. Meta-stupid. Stupid collapsed on itself so far that even the neutrons have collapsed. Stupid gotten so dense that no intellect can escape. Singularity stupid. Blazing hot mid-day sun on Mercury stupid. You emit more stupid in one second than our entire galaxy emits in a year. Quasar stupid. Your writing has to be a troll. Nothing in our universe can really be this stupid. Perhaps this is some primordial fragment from the original big bang of stupid. Some pure essence of a stupid so uncontaminated by anything else as to be beyond the laws of physics that we know. I'm sorry. I can't go on. This is an epiphany of stupid for me. After this, you may not hear from me again for a while. I don't have enough strength left to deride your ignorant questions and half baked comments about unimportant trivia, or any of the rest of this drivel. Duh.`,
  `Maybe later in life, after you have learned to read, write, spell, and count, you will have more success. True, these are rudimentary skills that many of us "normal" people take for granted that everyone has an easy time of mastering. But we sometimes forget that there are "challenged" persons in this world who find these things more difficult. I wish you the best of luck in the emotional, and social struggles that seem to be placing such a demand on you.`,
  `You are hypocritical, greedy, violent, malevolent, vengeful, cowardly, deadly, mendacious, meretricious, loathsome, despicable, belligerent, opportunistic, barratrous, contemptible, criminal, fascistic, bigoted, racist, sexist, avaricious, tasteless, idiotic, brain-damaged, imbecilic, insane, arrogant, deceitful, demented, lame, self-righteous, byzantine, conspiratorial, satanic, fraudulent, libelous, bilious, splenetic, spastic, ignorant, clueless, illegitimate, harmful, destructive, dumb, evasive, double-talking, devious, revisionist, narrow, manipulative, paternalistic, fundamentalist, dogmatic, idolatrous, unethical, cultic, diseased, suppressive, controlling, restrictive, malignant, deceptive, dim, crazy, weird, dystopic, stifling, uncaring, plantigrade, grim, unsympathetic, jargon-spouting, censorious, secretive, aggressive, mind-numbing, arassive, poisonous, flagrant, self-destructive, abusive, socially-retarded, puerile, clueless, and generally Not Good.`,
]

//thoughtcatalog.com/january-nelson/2021/01/best-insults/
https: Insults.push.apply(Insults, [
  `I was today years old when I realized I didn’t like you. Someday you’ll go far. And I really hope you stay there. Oops, my bad. I could’ve sworn I was dealing with an adult. I love what you’ve done with your hair. How do you get it to come out of your nostrils like that? Remember that time you were saying that thing I didn’t care about? Yeah, that is now.`,
  `You’re the reason God created the middle finger. I’m busy right now, can I ignore you another time? Oh, you don’t like being treated the way you treat me? That must suck. I wish I had a flip phone, so I could slam it shut on this conversation. N’Sync said it best, “BYE, BYE, BYE!” I’ve been called worse things by better men.`,
  `You’re a gray sprinkle on a rainbow cupcake. Your secrets are always safe with me. I never even listen when you tell me them. You bring everyone so much joy! You know, when you leave the room. But, still. How many licks until I get to the interesting part of this conversation? Keep rolling your eyes, you might eventually find a brain. Your face makes onions cry. Did I invite you to the barbecue? Then why are you all up in my grill?`,
  `Our kid must have gotten his brain from you! I still have mine. You have so many gaps in your teeth it looks like your tongue is in jail. If your brain was dynamite, there wouldn’t be enough to blow your hat off. You are more disappointing than an unsalted pretzel. It’s impossible to underestimate you.`,
  `Wow, your maker really didn’t waste time giving you a personality, huh? Her teeth were so bad she could eat an apple through a fence. I’ll never forget the first time we met. But I’ll keep trying. Oh, I’m sorry. Did the middle of my sentence interrupt the beginning of yours? Hold still. I’m trying to imagine you with personality. I’m not insulting you, I’m describing you. You are the human version of period cramps. You’re cute. Like my dog. He also chases his tail for entertainment. You are like a cloud. When you disappear, it’s a beautiful day.  You have an entire life to be an idiot. Why not take today off? Your kid is so annoying, he makes his Happy Meal cry. Your face is just fine, but we’ll have to put a bag over that personality. I’m not a nerd. I’m just smarter than you.`,
  `I may love to shop but I will never buy your bull. Child, I’ve forgotten more than you ever knew. I’m an acquired taste. If you don’t like me, acquire some taste. Bye. Hope to see you never. Don’t worry, the first 40 years of childhood are always the hardest. If you’re going to be two-faced, at least make one of them pretty. If you have a problem with me, write the problem on a piece of paper, fold it, and shove it up your ass.`,
  `Complete this sentence for me: “I never want to see you ————!” I thought of you today. It reminded me to take out the trash. You bring everyone so much joy when you leave the room. Did the mental hospital test too many drugs on you today? OH MY GOD! IT SPEAKS! Beauty is only skin deep, but ugly goes clean to the bone. I’d like to help you out. Which way did you come in?`,
  `I forgot the world revolves around you. My apologies, how silly of me.Light travels faster than sound which is why you seemed bright until you spoke.I’d rather treat my baby’s diaper rash than have lunch with you. You look so pretty. Not at all gross, today.I only take you everywhere I go, so I don’t have to kiss you goodbye.We were happily married for one month, but unfortunately, we’ve been married for 10 years.When you look in the mirror, say hi to the clown you see in there for me, would you?`,
  `Somewhere out there is a tree tirelessly producing oxygen for you. You owe it an apology. That sounds like a you problem. You have miles to go before you reach mediocre. I see no evil, and I definitely don’t hear your evil. I’m just glad that you’re stringing words into sentences now. Don’t worry about me. Worry about your eyebrows. Mirrors can’t talk. Lucky for you, they can’t laugh, either. You just might be why the middle finger was invented in the first place.`,
  `You are proof God has a sense of humor. If I had a face like yours, I would sue my parents. You must have been born on a highway. That’s where most accidents happen. Grab a straw, because you suck. You’re the reason the gene pool needs a lifeguard. If laughter is the best medicine, your face must be curing the world.`,
  `I’m glad to see you’re not letting education get in the way of your ignorance. If I wanted to kill myself, I would climb to your ego and jump to your IQ. I’d agree with you but then we’d both be wrong. Your only chance of getting laid is to crawl up a chicken butt and wait. Comebacks to use on your best friends and family`,
  `Don’t be ashamed of who you are. That’s your parent’s job. I told my therapist about you. Take my lowest priority and put yourself beneath it. If you were an inanimate object, you’d be a participation trophy. Hey, you have something on your chin. No, the 3rd one down. I hope your wife brings a date to your funeral.`,
  `People like you are the reason God doesn’t talk to us anymore. You are a pizza burn on the roof of the world’s mouth. If genius skips a generation, your children will be brilliant. You’re my favorite person… besides every other person I’ve ever met. You’re about as useful as a screen door on a submarine. I believed in evolution until I met you.`,
  `You are proof that evolution can go in reverse. If your brain was dynamite, there wouldn’t be enough to blow your hat off. Unless your name is Google, stop acting like you know everything! I know you are, but what am I? Yeah? Well, you smell like hot dog water. Isn’t it dangerous to use your whole vocabulary in one sentence? Sorry, not sorry.`,
  `If I had a dollar for every time you said something smart, I’d be broke. I do not consider you a vulture. I consider you something a vulture would eat. If I throw a stick, will you leave? In the land of the witless, you would be king. I would prefer a battle of wits, but you appear unarmed. I like the way you try. I’m jealous of all the people who haven’t met you. People clap when they see you. They clap their hands over their eyes. When I see your face, there’s not a thing that I would change… except the direction I was walking in. You look like something I would draw with my left hand. I look ugly? Good. I was trying to look like you today.`,
  `I would never date you. I’m lonely, not desperate. I don’t have the patience or the crayons to explain this to you. My days of not taking you seriously are certainly coming to a middle. I’d say you’re ‘dumb as a rock,’ but at least a rock can hold a door open. I bet your parents change the subject when their friends ask about you. You’re a conversation starter. Not when you are around, but once you leave. First off: Brush your teeth.`,
  `I find the fact that you’ve lived this long both surprising and disappointing. You’re impossible to underestimate. You should carry a plant around with you to replace the oxygen you waste. Somewhere, somehow, you are robbing a village of their idiot. You are the reason why shampoo has instructions. I’d give you a nasty look, but you’ve already got one.`,
  `Mister Rogers would be disappointed with you. You must have to sneak up on your hand to masturbate. If you were the light at the end of the tunnel, I’d turn back around. Were you born this stupid or did you take lessons? You should really come with a warning label. I don’t know what your problem is, but I’m guessing it’s hard to pronounce.`,
  `If I wanted to hear from an asshole, I’d fart.`,
  `I will ignore you so hard you will start doubting your existence. Stupidity isn’t a crime, so you’re free to go. Too bad you can’t Photoshop your ugly personality. Don’t you get tired of putting makeup on your two faces every morning? The people who tolerate you on a daily basis are the real heroes. You see that door? I want you on the other side of it.`,
  `Please just tell me you don’t plan to home-school your kids. If you’re going to act like a turd, go lay on the yard. If ignorance is bliss, you must be the happiest person on the planet. Isn’t there a bullet somewhere you could be jumping in front of? Jesus might love you, but everyone else definitely thinks you’re an idiot. You look like a ‘before’ picture.`,
  `Good story, but in what chapter do you shut up? May both sides of your pillow be uncomfortably warm. I am returning your nose. I found it in my business. What doesn’t kill you, disappoints me. Jealousy is a disease. Get well soon. I could eat a bowl of alphabet soup and poop out a smarter statement than whatever you just said. Don’t hate me because I’m beautiful. Hate me because your boyfriend thinks so. Your only purpose in life is to become an organ donor. Who ate your bowl of sunshine this morning, thundercloud? Earth is full. Go home. You’re about as useful as an ashtray on a motorcycle. There are some remarkably dumb people in this world. Thanks for helping me understand that. Aww, it’s so cute when you try to talk about things you don’t understand. You fear success, but you really have nothing to worry about. The last time I saw a face like yours, I fed it a banana. As an outsider, what do you think of the human race?`,
  `Don’t feel bad. A lot of people have no talent. Don’t try to think too hard. You’re so stupid it might sprain your brain. Did your parents ever ask you to run away from home? You’re living proof it’s possible to live without a brain. How much of a refund do you expect on your head, since it’s empty? Brains aren’t everything. In your case, they’re nothing. I have seen people like you. But I had to pay admission.`,
  `Are you ever overwhelmed with the urge to tell someone to shut up? Because that’s how I feel right now.Two wrongs don’t make a right. Take your parents, for instance.I’d slap you but I don’t want to make your face look any better.I will slap you so hard even Google won’t be able to find you.One day, I hope you’ll choke on the crap you talk.You have a face only a mother could love.`,
  `If I said anything to offend you it was purely intentional. I hope your next blowjob is from a shark. You’re a bad person. Enough said. You’re the type of person who can’t read the room. You don’t understand when you aren’t wanted.`,
])

Insults.push.apply(Insults, [
  `I have nothing to say to you. You are a walking pile of garbage. Your breath smells like rotting fish and dead flowers. You have more holes in your head than Swiss cheese. You look like you were mugged by a gorilla and left for dead.`,
  `Your hair is greasier than a seal's fur. Your eyes are as blue as a dirty diaper. You have a face that could stop traffic, but it doesn't. Your breath is worse than a garbage truck on a hot day. You should be ashamed of yourself, but you aren't. You make me want to stick my head in an oven.`,
  `You are a walking disaster area. Your smile looks like it was painted on with a fork. You have more zits than a teenager's acne-prone forehead.`,
  `Your laugh sounds like a hyena with a cold. You have more baggage than a Samsonite commercial. Your personality is as dull as watching paint dry.`,
  `You are as charming as a root canal without novocaine. Your fashion sense makes me want to vomit. You have more enemies than the mob boss from The Godfather. Your breath smells like a sewer full of rotting fish. You are a walking talking pile of crap. Your hair is so greasy I can see the light bulb above your head. You look like you just came out of a weeklong drug binge.`,
  `Your breath stinks so bad, it could knock over a linebacker. You have more scars and wrinkles than a prune. Your smile is as fake as a politician's promise. You make me want to take a shower after looking at you. Your breath is worse than a skunk's morning coffee. You should be ashamed of yourself for being such a loser. You are a walking disaster waiting to happen.`,
])
